PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:<http://www.w3.org/2008/05/skos-xl#>

    SELECT ?s ?p ?o

    WHERE {
        ?s ?p ?o
                    }
    LIMIT 10
    OFFSET 100
